version: "3"

includes:
  sub_tasks:
    taskfile: ./sub_tasks.yml

tasks:
  1_create_vpc_resources:
    summary: |
      Step 1 - Create a VPC
      Step 2 - Create a Public Subnet
      Step 3 - Create a Route table
      Step 4 - Create a Internet Gateway
      Step 5 - Create a Security Group
    cmds:
      - task sub_task:create_vpc
      - task sub_task:create_public_subnet
      - task sub_task:create_public_route_table_for_public_subnet
      - task sub_task:create_int_gw
      - task sub_task:create_sec_group_for_ec2
    
  2_complete_vpc_setup:
    summary: | 
      Step 6 - allow_public_subnet_to_auto_assign_ipv4_address
      Step 7 - attach_int_gw_to_vpc
      Step 8 - create_route_in_route_table
      Step 9 - associate_public_subnet_in_route_table
      Step 10 - allow_ssh_port_access_in_sg
    cmds:
      - task sub_task:allow_public_subnet_to_auto_assign_ipv4_address
      - task sub_task:attach_int_gw_to_vpc
      - task sub_task:create_route_in_route_table
      - task sub_task:associate_public_subnet_in_route_table
      - task sub_task:create_sec_group_for_ec2
  
  3_create_ec2_resources:
    summary:  |
      Step 11 -  generate_ec2_key_pair
      Step 12 - create_ec2_instance
    cmds:
      - task sub_task:generate_ec2_key_pair
      - task sub_task:create_ec2_instance

  4_ssh_into_ec2_instance:
    summary: |
      Step 13 - running_ec2_instance_details
      Step 14 - ssh_into_the_ec2_instance
    cmds:
      - task sub_task:running_ec2_instance_details
      - task sub_task:ssh_into_the_ec2_instance

  5_cleanup_the_ec2_instance:
    summary: |
      Step 15 -  stop_ec2_instance
      Step 16 - terminate_ec2_instance
    cmds:
      - task sub_task:stop_ec2_instance
      - task sub_task:terminate_ec2_instance
  
  6_cleanup_other_resources:
    summary: |
      Step 17 - delete_security_group
      Step 18 - modify_public_subnet_attribute
      Step 19 - delete_public_route_table, delete_intetnet_gateway and delete_subnet
      Step 20 - delete_vpc
    cmds:
      - task sub_task:delete_security_group
      - task sub_task:modify_public_subnet_attribute
      - task sub_task:delete_public_route_table
      - task sub_task:delete_intetnet_gateway
      - task sub_task:delete_subnet 
      - task sub_task:delete_vpc

