version: '3'

vars:
  global_variable: Hello

tasks:
  run_same_task_multiple_times_with_different_variables:
    cmds:
      - task: length_of_word
        vars: { SOME_VAR: 'case 1' }
      - task: length_of_word
        vars: { SOME_VAR: 'someother case 2' }
        silent: true

  length_of_word:
    cmds:
      - echo {{.SOME_VAR}} | wc -c 
    silent: true
  
  print-global-variable:
    # both underscores and hyphens are accepted in the task name
    cmds:
      - echo {{.global_variable}}
    silent: true